install.packages("pkgconfig")
install.packages("tseries")
install.packages("ggplot2")
install.packages("fpp2")
install.packages("fpp")
library(pkgconfig)
library(tseries)
library(fpp)
library(fpp2)
library(ggplot2)
library(readxl)

byclient <- read.csv("C:/Users/timot/Dropbox/Educational/MSBA/Independent/Serenova/Serenova_TimeSeries_Samples/DatabyClient.csv")
bycampaign <- read_excel("C:/Users/timot/Dropbox/Educational/MSBA/Independent/Serenova/Serenova_TimeSeries_Samples/ByCampaign.xlsx")
View(bycampaign)
